In [1]:
from utils import final_candidate_words

In [2]:
from torch import tensor

In [3]:
final_candidate_words('पुस्तकलयबाटे',use_trie = True)

['पुस्तकालयबाट', 'पुस्तकलयबाटे']

In [4]:
final_candidate_words('पुस्तकलयबाटे')

['पुस्तकालयबाट', 'पुस्तकलयबाटे']

In [5]:
final_candidate_words('थुलो')

['ठुलो', 'ठूलो', 'थुलो', 'ठुला', 'थलो', 'धुलो', 'धूलो']

In [3]:
sample_sentences = ['हरेक सेपालीले नेपामको संविधानक पालना गर्नुपर्छ ।' ,
                    'म पुस्तकलयबाटे थुलो किताब पढ्न चाहन्छु ।',
                    'तर उस समयमा पनि स्वस्थ राजनैतिक वातावरणको अभावले गर्दा देश विकासतर्फ विशेष प्रगति हुन  सकेन।',
                   'नेपालमा आधुनिक रुपमा आर्थक विकाससम्बन्धी कार्यरू प्रारम्भ भएको हालै मात्र हो।',
                   'हार धुनुहोस् र स्वास्थ जीवन जिउनुहोस्।',
                   'जब प्रवीधिहरू एकीकृत हुन सूरु गर्छन् अर्थतन्त्र तथ सँस्कृति पनि निश्चितरूपमा विस्तारै एकीकृत हुने छ।',
                   'उद्देयहरुमा पनि कुनै एक उद्देश्य पूर्ति नहुँदै अर्को नयाँ  उद्देश्यको रुपमा लिइने परम्परा बस्यो।',
                   'लगानीकर्ताहरूको धयान तुरुन्त फेरियो , व्यापारीहरूले वताए ।',
                    'अति धेरै हिज्जे गलती भएका शब्दहरू । तपाईँले टाइप गर्दा हिज्जे जाँच अक्षम पारयो ।',
                    'लामो'
                   ]

# Testing with Knesner ney Language model

In [ ]:
from corrector import extract_choices,return_choices2

In [ ]:
import pickle
with open('models/saved_model_knlm2','rb') as inputfile:
    kn_lm2 = pickle.load(inputfile) 

In [9]:
extract_choices(sample_sentences[8],model=kn_lm2,p_lambda = 0.3,trie = True,likelihood = 'bm')

[['अति', 'ति', 'अनि', 'अलि', 'यति'],
 ['धेरै'],
 ['हिज्जे'],
 ['गलत'],
 ['भएको', 'भएका'],
 ['शब्दहरू', 'शब्दहरु'],
 ['।'],
 ['तपाईंले', 'तपाईँले'],
 ['लाइक', 'पाप', 'टाइप', 'पाइप', 'टाइम'],
 ['गर्दा', 'गर्दै'],
 ['हिज्जे', 'हिड्ने'],
 ['जाँच', 'पाँच'],
 ['अक्षम', 'कक्षमा', 'अक्षय', 'अक्षर', 'सक्षम', 'पक्षमा'],
 ['पारयो', 'पायो', 'पाइयो', 'पारा', 'परको', 'पारस'],
 ['।'],
 []]

In [10]:
extract_choices(sample_sentences[1],model=kn_lm2,p_lambda = 0.0,trie = True,likelihood = 'default')

[['म'],
 ['पुस्तकलयबाटे', 'पुस्तकालयबाट'],
 ['थुलो', 'ठुलो', 'धूलो', 'ठूलो', 'धुलो', 'थलो', 'ठुला'],
 ['किताब', 'पिसाब', 'हिसाब'],
 ['पढ्न'],
 ['चाहन्छु', 'चाहिन्छ', 'चाहन्छन्', 'चाहन्थे', 'चाहन्छौं', 'चाहन्छ'],
 ['।', 'ई', 'ओ', 'ः', 'अ'],
 []]

In [11]:
wc,wp = return_choices2(sample_sentences[2],model=kn_lm2,p_lambda = 0.3,trie = True,likelihood = 'bm')

In [17]:
wc

[[('तर', 'आस', 'समयमा', 'पनि', 'स्वस्थ'),
  ('तर', 'उप', 'समयमा', 'पनि', 'स्वस्थ'),
  ('तर', 'उस', 'समयमा', 'पनि', 'स्वस्थ'),
  ('तर', 'स', 'समयमा', 'पनि', 'स्वस्थ'),
  ('कर', 'उस', 'समयमा', 'पनि', 'स्वस्थ'),
  ('तार', 'उस', 'समयमा', 'पनि', 'स्वस्थ'),
  ('तर', 'आस', 'समयको', 'पनि', 'स्वस्थ'),
  ('तर', 'आस', 'सहरमा', 'पनि', 'स्वस्थ'),
  ('पर', 'स', 'समयमा', 'पनि', 'स्वस्थ'),
  ('तर', 'आस', 'समयमा', 'पनि', 'अस्वस्थ')],
 [('स्वस्थ', 'राजनीतिक', 'वातावरणको', 'अभावले', 'गर्दा'),
  ('अस्वस्थ', 'राजनीतिक', 'वातावरणको', 'अभावले', 'गर्दा'),
  ('स्वस्थ', 'राजनैतिक', 'वातावरणको', 'अभावले', 'गर्दा'),
  ('स्वस्थ', 'राजनैतिक', 'वातावरणमा', 'अभावले', 'गर्दा'),
  ('अस्वस्थ', 'राजनीति', 'वातावरणको', 'अभावले', 'गर्दा'),
  ('स्वस्थ', 'राजनीतिक', 'वातावरणमा', 'अभावले', 'गर्दा'),
  ('स्वस्थ', 'राजनीतिक', 'वातावरणको', 'अभावमा', 'गर्दा'),
  ('स्वस्थ', 'राजनीतिक', 'वातावरणको', 'अभावले', 'पर्दा'),
  ('स्वस्थ', 'राजनीतिक', 'वातावरणको', 'अभावले', 'गर्न'),
  ('अस्वस्थ', 'राजनीतिका', 'वातावरणको', 'अभावले', 'गर्दा'

In [7]:
list(zip(wc,wp))

[([('तर', 'आस', 'समयमा', 'पनि', 'स्वस्थ'),
   ('तर', 'उप', 'समयमा', 'पनि', 'स्वस्थ'),
   ('तर', 'उस', 'समयमा', 'पनि', 'स्वस्थ'),
   ('तर', 'स', 'समयमा', 'पनि', 'स्वस्थ'),
   ('कर', 'उस', 'समयमा', 'पनि', 'स्वस्थ'),
   ('तार', 'उस', 'समयमा', 'पनि', 'स्वस्थ'),
   ('तर', 'आस', 'समयको', 'पनि', 'स्वस्थ'),
   ('तर', 'आस', 'सहरमा', 'पनि', 'स्वस्थ'),
   ('पर', 'स', 'समयमा', 'पनि', 'स्वस्थ'),
   ('तर', 'आस', 'समयमा', 'पनि', 'अस्वस्थ')],
  [-46.05453056303696,
   -46.44032601243608,
   -48.11849540168839,
   -48.93666063888338,
   -49.32341562437037,
   -49.91554247405139,
   -50.00966664269788,
   -50.014672315846965,
   -50.05962883299812,
   -50.08154654631848]),
 ([('स्वस्थ', 'राजनीतिक', 'वातावरणको', 'अभावले', 'गर्दा'),
   ('अस्वस्थ', 'राजनीतिक', 'वातावरणको', 'अभावले', 'गर्दा'),
   ('स्वस्थ', 'राजनैतिक', 'वातावरणको', 'अभावले', 'गर्दा'),
   ('स्वस्थ', 'राजनैतिक', 'वातावरणमा', 'अभावले', 'गर्दा'),
   ('अस्वस्थ', 'राजनीति', 'वातावरणको', 'अभावले', 'गर्दा'),
   ('स्वस्थ', 'राजनीतिक', 'वातावरणमा', '

# Testing with transformer model

In [1]:
from transformer import model
import torch

In [2]:
from corrector import extract_choices

In [3]:
model.load_state_dict(torch.load('models/transformer_model.pt'))

<All keys matched successfully>

In [4]:
from corrector import correctize_with_window_nn

In [5]:
from corrector import correctize_with_window_nn_

In [6]:
from corrector import transformer_probab_final_word

In [7]:
from corrector import correct_current_word,extract_choices_word

In [54]:
sample_sentences = ['हरेक सेपालीले नेपामको संविधानक पालना गर्नुपर्छ ।' ,
                    'म पुस्तकलयबाटे थुलो किताब पढ्न चाहन्छ ।',
                    'तर उस समयमा पनि स्वस्थ राजनैतिक वातावरनको अभावले गर्दा देश विकासतर्फ विशेष प्रगति हुन  सकेन।',
                   'नेपालमा आधुनिक रुपमा आर्थक विकाससम्बन्धी कार्यरू प्रारम्भ भएको हालै मात्र हो।',
                   'हार धुनुहोस् र स्वास्थ जीवन जिउनुहोस्।',
                   'जब प्रवीधिहरू एकीकृत हुन सूरु गर्छन् अर्थतन्त्र तथ सँस्कृति पनि निश्चितरूपमा विस्तारै एकीकृत हुने छ।',
                   'उद्देयहरुमा पनि कुनै एक उद्देश्य पूर्ति नहुँदै अर्को नयाँ  उद्देश्यको रुपमा लिइने परम्परा बस्यो।',
                   'लगानीकर्ताहरूको धयान तुरुन्त फेरियो , व्यापारीहरुले वताए ।',
                    'अति धेरै हिज्जे गलती भएका शब्दहरू । तपाईँले टाइप गर्दा हिज्जे जाँच अक्षम पारयो ।',
                    'लामो',
                    'म नेपाली राम्रोसँग बोल्दिन',
                    'तपाईंको उमर कति हो?',
                    'मलाइ एक्लै छोडनुहोस्']

In [55]:
def select_tokens(i,j):
    s = sample_sentences[i].split()[:j]
    return ' '.join(s)
    

In [56]:
extract_choices_word(sample_sentences[7],model = model,p_lambda = 1.2,l_lambda = 1,trie = True,likelihood = 'bm')

['लगानीकर्ताहरूको']
[['लगानीकर्ताहरूले', 'लगानीकर्ताहरूको']]
['लगानीकर्ताहरूको', 'धयान']
[['धयान', 'चयन', 'ढलान', 'धरान', 'ध्यान']]
Sentence tensor: tensor([[49637]], device='cuda:0')
tensor([120302,   1256,  12776,   3515,    395])
tensor([[[ -5.4038,  -6.9246,  -6.6446,  ..., -16.7893, -17.6532, -14.5671]]],
       device='cuda:0', grad_fn=<LogSoftmaxBackward0>) torch.Size([1, 1, 342570]) 1
tensor([-15.0798,  -8.7590, -13.1836, -11.8794,  -5.8402], device='cuda:0',
       grad_fn=<IndexBackward0>)
tensor([120302,   1256,  12776,   3515,    395])
tensor([291376, 135442, 185037,  ...,     15,    125,      5], device='cuda:0')
tensor([4, 1, 3, 2, 0], device='cuda:0')
जान्छु न्यूनीकरण दफा चाहन्छु
['ध्यान', 'चयन', 'धरान', 'ढलान', 'धयान']
Prod: धयान -3.233888198770077
Prod: चयन -7.645643976661007
Prod: ढलान -13.87074097045683
Prod: धरान -4.536347949810668
Prod: ध्यान -5.349780437650195
[['धयान', 'चयन', 'ढलान', 'धरान', 'ध्यान']] [tensor(-21.3297, grad_fn=<AddBackward0>), tensor(-18.1565, gr

[['लगानीकर्ताहरूले', 'लगानीकर्ताहरूको'],
 ['ध्यान', 'चयन', 'धरान', 'धयान', 'ढलान'],
 ['तुरुन्त', 'तुरुन्तै', 'दुरुस्त'],
 ['फेरियो', 'भेटियो', 'फेरिएको', 'गरियो', 'हरियो'],
 ['व्यापारीहरुले', 'व्यापारीहरूले'],
 ['बताए', 'वताए', 'कता', 'गराए', 'वटा'],
 ['।', 'आ', 'ः', 'इ', 'अ']]

In [47]:
correct_current_word('जब प्रविधिहरू एकीकृत हुन सूरु गर्छन् अर्थतन्त्र तथा सँस्कृति पनि निश्चितरूपमा',model=model,p_lambda = 1.2,l_lambda = 1,trie = True,likelihood = 'bm')

['जब', 'प्रविधिहरू', 'एकीकृत', 'हुन', 'सूरु', 'गर्छन्', 'अर्थतन्त्र', 'तथा', 'सँस्कृति', 'पनि', 'निश्चितरूपमा']
[['निश्चितरुपमा', 'निश्चितरूपमा']]
Sentence tensor: tensor([[  680],
        [44119],
        [ 1350],
        [   37],
        [56618],
        [  377],
        [ 2651],
        [   14],
        [21666],
        [    5]], device='cuda:0')
tensor([ 88584, 122294])
tensor([[[ -5.6213,  -6.1727,  -4.2060,  ..., -16.5473, -16.6862, -17.2982]],

        [[ -3.8301,  -4.6486,  -3.1276,  ..., -17.2521, -15.2524, -19.2046]],

        [[ -4.1067,  -6.2689,  -3.2926,  ..., -15.9814, -15.4236, -17.2361]],

        ...,

        [[ -4.3750, -10.2782,  -8.2561,  ..., -15.6630, -18.0608, -16.0671]],

        [[ -5.2898,  -6.7618,  -4.0764,  ..., -17.2819, -15.3262, -16.6465]],

        [[ -5.4032,  -3.9699,  -5.5404,  ..., -14.8377, -16.6672, -15.7660]]],
       device='cuda:0', grad_fn=<LogSoftmaxBackward0>) torch.Size([10, 1, 342570]) 10
tensor([-13.3704, -13.8763], device='cuda:0', gra

['निश्चितरुपमा', 'निश्चितरूपमा']

In [11]:
len(sample_sentences[1])

39

In [12]:
transformer_probab_final_word(sample_sentences[1])

RuntimeError: shape '[39, -1]' is invalid for input of size 33

In [ ]:
correctize_with_window_nn(sample_sentences[2],model=model,p_lambda = 0.8,trie = True,likelihood = 'bm')

In [ ]:
correctize_with_window_nn_(sample_sentences[2],model=model,p_lambda = 0.8,trie = True,likelihood = 'bm')

In [ ]:
wc,wp = return_choices2(sample_sentences[4],model=model,p_lambda = 1.5,trie = True,likelihood = 'bm',model_type = 'transformer')

In [ ]:
extract_choices(sample_sentences[-1],model=model,p_lambda = 1.5,trie = True,likelihood = 'bm',model_type = 'transformer')

In [ ]:
wc

In [ ]:
wc,wp = return_choices2(sample_sentences[1],model=model,p_lambda = 1.5,trie = True,likelihood = 'bm',model_type = 'transformer')

In [ ]:
wc

In [ ]:
list(zip(wc,wp))

In [ ]:
wc

In [ ]:
# extract_choices(a,model=model,p_lambda = 1.5,trie = True,likelihood = 'bm',model_type = 'transformer')

In [ ]:
# Substitution based 

In [22]:
a = 'तिमीलै कता जाना मन छ ?'
b = 'आज मा स्कुल जादिन'
c = 'तिमि यता आऊ त !'

In [23]:
sample_sentences = ['हरेक सेपालीले नेपामको संविधानक पालना गर्नुपर्छ ।' ,
                    'म पुस्तकलयबाटे थुलो किताब पढ्न चाहन्छ ।',
                    'तर उस समयमा पनि स्वस्थ राजनैतिक वातावरणको अभावले गर्दा देश विकासतर्फ विशेष प्रगति हुन  सकेन।',
                   'नेपालमा आधुनिक रुपमा आर्थक विकाससम्बन्धी कार्यरू प्रारम्भ भएको हालै मात्र हो।',
                   'हार धुनुहोस् र स्वास्थ जीवन जिउनुहोस्।',
                   'जब प्रवीधिहरू एकीकृत हुन सूरु गर्छन् अर्थतन्त्र तथ सँस्कृति पनि निश्चितरूपमा विस्तारै एकीकृत हुने छ।',
                   'उद्देयहरुमा पनि कुनै एक उद्देश्य पूर्ति नहुँदै अर्को नयाँ  उद्देश्यको रुपमा लिइने परम्परा बस्यो।',
                   'लगानीकर्ताहरूको धयान तुरुन्त फेरियो , व्यापारीहरूले वताए ।',
                    'अति धेरै हिज्जे गलती भएका शब्दहरू । तपाईँले टाइप गर्दा हिज्जे जाँच अक्षम पारयो ।',
                    'लामो',
                    'म नेपाली राम्रोसँग बोल्दिन',
                    'तपाईंको उमर कति हो?',
                    'मलाइ एक्लै छोडनुहोस्',
                    c,
                    b,
                    a
                    
                   ]

In [57]:
extract_choices(sample_sentences[7],model=model,p_lambda = 0.8,trie = True,likelihood = 'bm',model_type = 'transformer')

Length of candidates: 300
In candidate_probabilities...
5
Done...
Length of candidates: 50
In candidate_probabilities...
1
Done...


[['लगानीकर्ताहरूको'],
 ['ध्यान', 'धयान'],
 ['तुरुन्त', 'तुरुन्तै'],
 ['फेरियो', 'फेरिएको', 'भेटियो'],
 ['व्यापारीहरुले', 'व्यापारीहरूले'],
 ['बताए', 'वताए', 'गराए', 'कता'],
 ['।', 'आ', 'ः'],
 [],
 []]

In [18]:
[' '.join(('म', 'पुस्तकालयबाट', 'ठुलो', 'किताब', 'पढ्न'))]

['म पुस्तकालयबाट ठुलो किताब पढ्न']

In [8]:
torch.flip(torch.tensor([torch.tensor(-143.8868),torch.tensor(-142.8868)]),dims = (0,))

tensor([-142.8868, -143.8868])

In [ ]:
#Limitation of transformer model : Less candidate sentences are genereated due to Computational issues